# 공용 설정 파일: config.yaml

# Pub/Sub 설정
pubsub:
  endpoint: "https://pub-sub.kr-central-2.kakaocloud.com"
  domain_id: "{프로젝트가 속한 조직 ID}"
  project_id: "{카카오클라우드의 프로젝트 ID}"
  topic_name: "{콘솔에서 생성한 토픽 이름}"
  topic_name_mk: "{생성할 토픽 이름}"
  topic_description: ""
  topic_retention_duration: "600s"
  sub_name: "{서브 스크립션 이름}"
  credential_id: "{액세스 키 ID}"
  credential_secret: "{보안 액세스 키}"

# 구독 설정
subscription:
  name: "구독 이름"

# Object Storage 서브스크립션 설정
object_storage_subscription:
  name: "{obj_sub로 만들 서브스크립션 이름}"
  bucket: "{Object Storage 버킷 이름}"
  export_interval_min: 10
  file_prefix: ""
  file_suffix: ".log"
  channel_count: 4
  max_channel_count: 10
  is_export_enabled: true

# 로그 설정
logging:
  filename: "traffic_generator.log"
  level: "INFO"

# 스레드 및 사용자 설정
threads:
  num_users: 20
  max_threads: 5
  actions_per_user: 30

# API 서버 정보
api:
  base_url: "{실제 로드밸런서/API 서버 IP/도메인}"
  endpoints:
    add_user: "add_user"
    delete_user: "delete_user"
    login: "login"
    logout: "logout"
    products: "products"
    product_detail: "product"
    search: "search"
    checkout_history: "checkout_history"
    categories: "categories"
    category: "category"
    cart_view: "cart/view"
    cart_add: "cart/add"
    cart_remove: "cart/remove"
    checkout: "checkout"
    add_review: "add_review"
    error_page: "error"
  time_sleep_range:
    min: 0.1
    max: 1.0

# 나이 구간 임계값
age_threshold:
  young: 25
  middle: 50
